# Generated by Django 5.2.12 on 2026-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_worked_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
